sudo: required

language: generic

services:
  - docker

script:
  - docker build -t desirableobjects/circleci:latest -f Dockerfile .
  - docker build -t desirableobjects/circleci:dind -f Dockerfile.dind .
  - docker build -t desirableobjects/circleci:chromium -f Dockerfile.chromium .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

after_success:
  - docker push desirableobjects/circleci:latest
  - docker push desirableobjects/circleci:dind
  - docker push desirableobjects/circleci:chromium