FROM desirableobjects/circleci:latest

RUN curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
RUN tar -xz -C /tmp -f /tmp/docker.tgz
RUN mv /tmp/docker/docker* /usr/bin/

RUN curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose