FROM desirableobjects/circleci:latest

RUN apk -U --no-cache add chromium

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/ci && \
    echo "ci:x:${uid}:${gid}:Ci,,,:/home/ci:/bin/bash" >> /etc/passwd && \
    echo "ci:x:${uid}:" >> /etc/group && \
    echo "ci ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ci && \
    chmod 0440 /etc/sudoers.d/ci && \
    chown ${uid}:${gid} -R /home/ci

USER ci
ENV HOME /home/ci